# The pipeline should trigger automatically on code pushes to the main branch of the Github repository.
name: Build and test
on:
  push:
    branches:
      - main
  # Assumed that we also need to test code on pull requests
  pull_request:
    branches:
      - main

jobs:
  # test: build and test
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image to run test
        run: docker build --target=test -t devops-test:test-latest .

      - name: Run tests
        run: docker run --network=none --rm devops-test:test-latest poetry run pytest -s

  # Deploy: Deploy the application to the production environment
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate image tag base on the commit hash
        run: |
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          echo "PROD_TAG=m-$COMMIT_HASH" >> $GITHUB_ENV
      - name: Build image for production
        run: docker build --no-cache -t devops-test:$PROD_TAG .
