name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
        - name: checkout repository
          uses: actions/checkout@v4
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Log in to Amazon ECR
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: 'us-west-2'
#         run: |
#           aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <your-ecr-repo>

#       - name: Build Docker image
#         run: |
#           docker build -t sample-app .

#       - name: Push Docker image to ECR
#         run: |
#           docker tag sample-app:latest <your-ecr-repo>/sample-app:latest
#           docker push <your-ecr-repo>/sample-app:latest

  test:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Poetry
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.5'
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run test
        run: poetry run pytest -s